Traceback (most recent call last):
  File "/home/mark/Projects/Uni/uh-master-thesis-artifact/notebooks/venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/mark/Projects/Uni/uh-master-thesis-artifact/notebooks/venv/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mark/Projects/Uni/uh-master-thesis-artifact/notebooks/venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/mark/Projects/Uni/uh-master-thesis-artifact/notebooks/venv/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/mark/Projects/Uni/uh-master-thesis-artifact/notebooks/venv/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mark/Projects/Uni/uh-master-thesis-artifact/notebooks/venv/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

sine_model = nn.ReLUFNN(input_size=1, output_size=1, hidden_size=1000, num_hidden_layers=1)
# If this file does not exist, run the preparation notebook of the demo app.
sine_model.load_state_dict(torch.load("../demo-app/models/pwl_geometric_sine.pt", weights_only=True))
sine_model.eval()

x_train = np.linspace(-2 * math.pi, 2 * math.pi, 10000)
y_train = np.array([math.sin(x) for x in x_train])

with torch.no_grad():
    predicted = (
        sine_model(torch.tensor(x_train, dtype=torch.float32).unsqueeze(1)).detach().numpy()
    )

fig, ax = plt.subplots()
ax.plot(x_train, predicted, "r", label="Neural Network approximation")
ax.legend()
plt.show(fig)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[19], line 3[0m
[1;32m      1[0m sine_model [38;5;241m=[39m nn[38;5;241m.[39mReLUFNN(input_size[38;5;241m=[39m[38;5;241m1[39m, output_size[38;5;241m=[39m[38;5;241m1[39m, hidden_size[38;5;241m=[39m[38;5;241m1000[39m, num_hidden_layers[38;5;241m=[39m[38;5;241m1[39m)
[1;32m      2[0m [38;5;66;03m# If this file does not exist, run the preparation notebook of the demo app.[39;00m
[0;32m----> 3[0m sine_model[38;5;241m.[39mload_state_dict([43mtorch[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m../demo-app/models/pwl_geometric_sine.pt[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mweights_only[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m)
[1;32m      4[0m sine_model[38;5;241m.[39meval()
[1;32m      6[0m x_train [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m-[39m[38;5;241m2[39m [38;5;241m*[39m math[38;5;241m.[39mpi, [38;5;241m2[39m [38;5;241m*[39m math[38;5;241m.[39mpi, [38;5;241m10000[39m)

File [0;32m~/Projects/Uni/uh-master-thesis-artifact/notebooks/venv/lib/python3.10/site-packages/torch/serialization.py:1319[0m, in [0;36mload[0;34m(f, map_location, pickle_module, weights_only, mmap, **pickle_load_args)[0m
[1;32m   1316[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mencoding[39m[38;5;124m"[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m pickle_load_args[38;5;241m.[39mkeys():
[1;32m   1317[0m     pickle_load_args[[38;5;124m"[39m[38;5;124mencoding[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;124m"[39m[38;5;124mutf-8[39m[38;5;124m"[39m
[0;32m-> 1319[0m [38;5;28;01mwith[39;00m [43m_open_file_like[49m[43m([49m[43mf[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m [38;5;28;01mas[39;00m opened_file:
[1;32m   1320[0m     [38;5;28;01mif[39;00m _is_zipfile(opened_file):
[1;32m   1321[0m         [38;5;66;03m# The zipfile reader is going to advance the current file position.[39;00m
[1;32m   1322[0m         [38;5;66;03m# If we want to actually tail call to torch.jit.load, we need to[39;00m
[1;32m   1323[0m         [38;5;66;03m# reset back to the original position.[39;00m
[1;32m   1324[0m         orig_position [38;5;241m=[39m opened_file[38;5;241m.[39mtell()

File [0;32m~/Projects/Uni/uh-master-thesis-artifact/notebooks/venv/lib/python3.10/site-packages/torch/serialization.py:659[0m, in [0;36m_open_file_like[0;34m(name_or_buffer, mode)[0m
[1;32m    657[0m [38;5;28;01mdef[39;00m [38;5;21m_open_file_like[39m(name_or_buffer, mode):
[1;32m    658[0m     [38;5;28;01mif[39;00m _is_path(name_or_buffer):
[0;32m--> 659[0m         [38;5;28;01mreturn[39;00m [43m_open_file[49m[43m([49m[43mname_or_buffer[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m
[1;32m    660[0m     [38;5;28;01melse[39;00m:
[1;32m    661[0m         [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m [38;5;129;01min[39;00m mode:

File [0;32m~/Projects/Uni/uh-master-thesis-artifact/notebooks/venv/lib/python3.10/site-packages/torch/serialization.py:640[0m, in [0;36m_open_file.__init__[0;34m(self, name, mode)[0m
[1;32m    639[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, name, mode):
[0;32m--> 640[0m     [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m([38;5;28;43mopen[39;49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../demo-app/models/pwl_geometric_sine.pt'

